=== kristoffer124/magento2-configuration-files/etc/productfeed_list.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="productfeed_list" type="productFeedList" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="productFeedList">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="productfeed" type="productfeed" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="productfeed">
        <xs:sequence>
            <xs:element name="feedname" />
            <xs:element name="feedpath" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== kristoffer124/magento2-configuration-files/etc/productfeed_list.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="productfeed_list.xsd">
    <productfeed_list>
        <productfeed>
            <feedname>google</feedname>
            <feedpath>googlefeed.xml</feedpath>
        </productfeed>
        <productfeed>
            <feedname>facebook</feedname>
            <feedpath>facebook.xml</feedpath>
        </productfeed>
        <productfeed>
            <feedname>google_shopping</feedname>
            <feedpath>googleshopping_feed.xml</feedpath>
        </productfeed>
    </productfeed_list>
</config>
